# Basic options
title: The blog 
author: serejandmyself
email: 
description: The "no bullshit" blog
twitter_username: sergeys1234
github_username:  serejandmyself
url: https://blocksult.com/

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-analytics
