# Basic options
title: Blocksult 
author: GitHub User
email: simanovskys@yandex.ru
description: No bullshit blog
twitter_username: sergeys1234
github_username:  serejandmyself
website: https://blocksult.com

# Build settings
markdown: kramdown
theme: minima
