# Basic options
title: The blog 
author: serejandmyself
email: 
description: The "no bullshit" blog. Here, you will find all the posts about crypto from blocksult.com and me - serejandmyself, on
crypto related topics, like - technology, anarchy, economics, anti-politics and others. No ads, no bullshit, no pictures.
twitter_username: sergeys1234
github_username:  serejandmyself

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-analytics
