# Basic options
title: The blog 
author: serejandmyself
email: 
description: The "no bullshit" blog
twitter_username: sergeys1234
github_username:  serejandmyself

# Build settings
markdown: kramdown
theme: minima

# Add ons
  plugins:
    - jekyll-seo-tag
